apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Documentation demo component
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: documentation
  lifecycle: production
  owner: guests
  system: examples
  providesApis: []